#!/usr/bin/env bash

PRJ_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DOCKER_PASSWORD=$(cat "./secrets/docker")

docker login --username syntetizado --password-stdin < ./secrets/docker
docker-compose -f "docker/docker-compose.yml" up --force-recreate -d