#!/usr/bin/env bash

docker login --username syntetizado --password-stdin < ./secrets/docker
docker-compose -f "docker/docker-compose.yml" up --force-recreate -d

if [ ! -f .env ]; then
    cp .env.example .env
fi

./composer install



echo "Preparing DB"

./cmd migrate
./cmd db:seed
