<?php

namespace App\Exceptions;

use Airzone\Shared\Exception\ApiException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof ApiException) {
            return $e->render();
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
